# Generated by Django 5.0.7 on 2024-07-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psba_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkedinfo',
            name='totalParkingTime',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='parkingspace',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
