# Generated by Django 5.0.7 on 2024-07-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psba_app', '0003_alter_parkingspace_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspace',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
